### PR TITLE
Italian translation with minor updates and fixes.

### PR DESCRIPTION
**Pull request by dmedri**

### CODE REVIEW

**Comment by dmedri** [comment]
The current Makefile needs some love to work fine with all the available languages (ja,it). Please, take care of it.

**Comment by sebp** [comment]
Thanks for contributing to the tutorial.

It seems that you were using outdated .pot files, because sometimes paragraphs in the middle of the text are still untranslated.

I pushed a branch " dmedri-master ", which updates the Makefile and instructions in the README. It is important that you run

```
make gettext
sphinx-intl update -p build/gettext/ -l it
```

to generate new .pot files and update your .po files.

**Comment by dmedri** [comment]
Ok, I did it already after some days ago. I've already .pot updated and new working translations. I'm closing this pull request, for a new one.

**Comment by dmedri** [comment]
Please, delete the branch dmedri-master. It's totally broken. I'll send new patches.

**Pull request closed without merging**
