### PR TITLE
Added section for treemodel filters, along with a full code example

### PR DESCRIPTION
**Pull request by hadware**
There was no section on filters, whereas the old PyGTK tutorial had one... I used the old one to figure out how it works, but i think it's interesting to migrate the old doc to the new one. 

There was also no truly complete code example in this chapter, i think adding one wasn't too much.

I'm not a native speaker so proof-read what i wrote if you think it globally fits your criteria.

PS: in the future, I think it also might be good to divide this section (or enrich it) to explain how filters work on TreeStore's, i wasn't able to find real tutorial on this matter. Same goes for TreeModelSort (even if it's redundant with the current Sort section, the class itself is more functionnal i think).

### CODE REVIEW

**Comment by sebp** [comment]
Thanks a lot, looks good!

**Comment by hadware** [comment]
I re-read it again, there are about 2-3 small mistakes that remained. I'm a bit new to github's "commit-protocol"... should I fix them on my own repo and make a pull-request, or would you prefer me point them out for you to correct them?.

Also, what about detailing on the TreeStore ?

**Comment by sebp** [comment]
Am 08.02.2015 um 17:36 schrieb Hadrien:
> I re-read it again, there are about 2-3 small mistakes that remained.
> I'm a bit new to github's "commit-protocol"... should I fix them on my
> own repo and make a pull-request, or would you prefer me point them out
> for you to correct them?.
> 
> Also, what about detailing on the TreeStore ?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebp/PyGObject-Tutorial/pull/64#issuecomment-73418441>.
> 

Please file a new pull request with the changes.

If you want to add more information to the TreeStore model, I'd very
much appreciate it. If you have an update to the existing documentation,
simply file a new pull request as well.

**Comment by hadware** [comment]
Got it, i'll take care of it as soon as i can!

**Pull request merged**
