### PR TITLE
Update license to LGPL

### LINKED ISSUE #222: Relicensing for combining with PyGObject
There is a project to centralize the PyGObject documentation which is underway: https://gitlab.gnome.org/GNOME/pygobject/-/issues/609.

One thing that would be nice would be to combine the [PyGObject Guide](https://gitlab.gnome.org/rafaelmardojai/pygobject-guide) which was derived from this project. Since it was derived from this project, it is licensed under the GFDL, but PyGObject, including the docs, is licensed under the LGPL.

How would you feel if we relicensed or dual licensed this project so that we could bring it back as part of a more central set of documentation?

## Agreed to License Change (48/62 or 77%)

1. @cjmayo - Yes
1. @sebp - Yes
1. @rffontenelle - Yes
1. @gianmt - Yes
1. @tshepang - Yes
1. @TingPing - Yes
1. @takeshi-aihana - Yes
1. @paretje - Yes
1. @lazka - Yes
1. @haaninjo - Yes
1. @mozbugbox - Yes
1. @abcleanonme - Yes
1. @TarasKuzyo - Yes
1. @mcrapet - Yes
1. @kam193 - Yes
1. @DevJac - Yes
1. @cydanil - Yes
1. @sam-m888 - Yes
1. @samdroid-apps - Yes
1. @shivdhar - Yes
1. @sharkwouter - Yes
1. @dispread - Yes
1. @ltsdw - Yes
1. @oddstr13 - Yes
1. @rst0git - Yes
1. @sullenel - Yes
1. @AlexanderStein - Yes
1. @ajphukan - Yes
1. @cas-- - Yes
1. @csicar - Yes
1. @giove91 - Yes
1. @k4rtik - Yes
1. @kamathln - Yes
1. @LunarEclipse363 - Yes
1. @mgedmin - Yes
1. @mark-summerfield - Yes
1. @MatheusNtg - Yes
1. @nicobatty - Yes
1. @NotAFile - Yes
1. @pwaring - Yes
1. @neynt - Yes
1. @anarcat - Yes 
1. @wolfv - Yes
1. @sebuls - Yes
1. @osamuaoki - Yes
1. @danyeaw - Yes
1. @danielquinn  - Yes (via email)
1. @liberforce - Ye (via email)

### PR DESCRIPTION
**Pull request by danyeaw**
PR to close #222 once we have a quorum of contributors agreeing to the change.

### CODE REVIEW

**Comment by sebp** [comment]
@danyeaw Could you please update the references at

https://github.com/sebp/PyGObject-Tutorial/blob/6c708c4cb9e14afa3f5fbbfa767b037bd9ae3ace/source/conf.py#L58

and 

https://github.com/sebp/PyGObject-Tutorial/blob/6c708c4cb9e14afa3f5fbbfa767b037bd9ae3ace/source/index.txt#L11

Thank you!

**Comment by danyeaw** [comment]
Hi @sebp, instead of putting the license info in the Copyright, would it be better to put something like `2011, Sebastian Pölsterl` like in the example here: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-copyright?

**Comment by sebp** [comment]
How about using the "The PyGObject community" instead of just my name, 
similar to 
https://github.com/scipy/scipy/blob/d6530f396e0556aa1cdd9bb9f1278efe76a7779b/doc/source/conf.py#L75

**Comment by danyeaw** [comment]
Hi @sebp, I like that! I updated the pull request with those changes.

**Pull request merged**
