### PR TITLE
Translations update

### PR DESCRIPTION
**Pull request by dmedri**
Updated templates to latest release available; a renewed italian translation; new location in translations/locale/*/LC_MESSAGES/ useful to build.

### CODE REVIEW

**Comment by dmedri** [comment]
The dmedri-master branch is totally broken, due to my mistakes and lack of skills on sphinx. I've now reworked my translation, using latest templates, building and testing docs. I've synced widgets names with the italian translation of Glade.

**Comment by sebp** [comment]
Please use the Makefile from commit c61fe9e7d0c00c9433eceb25e8b99f56e679b0d3 and squash your changes related to the Japanese and Italian translation, respectively.

**Comment by dmedri** [comment]
Please, those changes fix the i18n build of your doc. You can try with my repository.

**Comment by sebp** [comment]
Closing due to inactivity. Feel free to reopen if you want to fix it.

**Pull request closed without merging**
