### PR TITLE
Update Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by sebp** [comment]
Thanks a lot! Please note that the update is not deployed to readthedocs yet. I need to figure at the best way to do this.

**Comment by sebp** [comment]
The updated translation is now being deployed to RTD. Thanks again.

**Comment by rffontenelle** [comment]
Awesome. Were you able to figure out how to specify the language to RTD ?

**Comment by sebp** [comment]
What do you mean? For deployment to RTD, you (well, I) need to create 
one project for each language and then link it to the main project.

**Comment by rffontenelle** [comment]
I thought it was going to be harder to put it on RTD. So, that's good.

**Pull request merged**
