### PR TITLE
Add a widget gallery page

### PR DESCRIPTION
**Pull request by lazka**
This came up in https://gitlab.gnome.org/GNOME/pygobject/issues/208

Add a list of all non-abstract Gtk.Widget subclasses and show an
example image for it. The images are taken from the gtk+ documentation.

The goal is that users can quickly get an overview of the available widgets
and to make it possible to find a widget type without knowing the name.

### CODE REVIEW

**Comment by lazka** [comment]
screenshot-2018-4-20 5 widget gallery python gtk 3 tutorial 3 4 documentation

**Comment by sebp** [comment]
Thanks a lot for the pull request. You added container widgets etc without an screenshot. I would remove those, because the only information they provide is their mere existence, but not what they can be used for.

**Comment by lazka** [comment]
> Thanks a lot for the pull request. You added container widgets etc without an screenshot. I would remove those, because the only information they provide is their mere existence, but not what they can be used for.

I left all possible widgets in so the remaining entries act as a todo list of sorts. But I don't feel strongly about it so I can remove them if you want.

**Comment by sebp** [comment]
Well, you can't really visualize container widgets, things like Popover, HBox, HButtonBox. I would remove those. In addition, it might be a good idea to indicate which widgets are deprecated.

**Comment by lazka** [comment]
Done.

It would still be possible to add some example usages of containers, like

popover
box

**Pull request merged**
